name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.4
          - php: "8.1"
            composer: --prefer-lowest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer update ${{ matrix.composer }}
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_php_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: composer test
